# Generated by Django 5.2.7 on 2025-10-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
