# Generated by Django 5.2.7 on 2025-10-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0005_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookissue",
            name="rental_period",
            field=models.PositiveIntegerField(default=14),
        ),
    ]
